name: VINS-Fusion
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=2.16=mkl
  - brotli-python=1.0.9=py37hd23a5d3_7
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.12.14=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cudatoolkit=11.6.2=hfc3e2af_13
  - eigen=3.4.0=h00ab1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h267a509_2
  - gmp=6.3.0=hac33072_2
  - gnutls=3.6.13=h85f3911_1
  - idna=3.10=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jpeg=9e=h0b41bf4_3
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.8.0=16_mkl
  - libcblas=3.8.0=16_mkl
  - libdeflate=1.14=h166bdaf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - liblapack=3.8.0=16_mkl
  - liblapacke=3.8.0=16_mkl
  - libnsl=2.0.1=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.4.0=h82bc61c_5
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.13=h4ab18f5_6
  - mkl=2020.2=256
  - ncurses=6.5=he02047a_1
  - nettle=3.6=he412f7d_0
  - numpy=1.21.6=py37h976b520_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.4.0=hb9d3cd8_0
  - orocos-kdl=1.5.1=h5888daf_8
  - plyfile=0.8.1=pyhd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyh415d2e4_2
  - pysocks=1.7.1=py37h89c1867_5
  - python=3.7.12=hf930737_100_cpython
  - python-orocos-kdl=1.5.1=py37hcd2ae1e_2
  - python_abi=3.7=2_cp37m
  - pytorch=1.12.1=py3.7_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h8228510_1
  - requests=2.32.2=pyhd8ed1ab_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - sqlite=3.46.0=h6d4b2fc_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=0.12.1=py37_cu116
  - torchvision=0.13.1=py37_cu116
  - tqdm=4.67.1=pyhd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - addict==2.4.0
      - argcomplete==3.1.2
      - attrs==24.2.0
      - backcall==0.2.0
      - catkin-pkg==1.0.0
      - click==8.1.8
      - comm==0.1.4
      - configargparse==1.7.1
      - cycler==0.11.0
      - dash==2.15.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - diff-gaussian-rasterization==0.0.0
      - diff-gaussian-rasterization-depth==0.0.0
      - docutils==0.20.1
      - empy==4.2
      - evo==1.16.0
      - fastjsonschema==2.21.2
      - flask==2.2.5
      - fonttools==4.38.0
      - fused-ssim==0.0.0
      - gnupg==2.3.1
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - ipython==7.34.0
      - ipywidgets==8.1.7
      - itsdangerous==2.1.2
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.3.2
      - jsonschema==4.17.3
      - jupyter-core==4.12.0
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.1.2
      - matplotlib-inline==0.1.6
      - natsort==8.4.0
      - nbformat==5.7.0
      - nest-asyncio==1.6.0
      - open3d==0.17.0
      - opencv-python==4.10.0.84
      - packaging==24.0
      - pandas==1.3.5
      - parso==0.8.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pip==24.0
      - pkgutil-resolve-name==1.3.10
      - plotly==5.18.0
      - prompt-toolkit==3.0.48
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pycryptodomex==3.21.0
      - pygments==2.17.2
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pyrsistent==0.19.3
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.1
      - retrying==1.4.2
      - rospkg==1.5.1
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - seaborn==0.12.2
      - simple-knn==0.0.0
      - six==1.16.0
      - tenacity==8.2.3
      - threadpoolctl==3.1.0
      - traitlets==5.9.0
      - wcwidth==0.2.14
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.14
      - zipp==3.15.0
prefix: /home/seu/anaconda3/envs/VINS-Fusion
