%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 760
image_height: 1008
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 297.780077
   fy: 297.780084
   cx: 384.158462
   cy: 495.528176
